# Generated by Django 4.2.3 on 2023-07-28 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('startingBid', models.PositiveIntegerField()),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('listedByUser', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('winner', models.CharField(blank=True, default='No one has made a bid', max_length=64, null=True)),
                ('watchlists', models.ManyToManyField(blank=True, default=None, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Listings',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200)),
                ('dateOfComment', models.DateTimeField(auto_now_add=True)),
                ('commentByUser', models.CharField(max_length=64)),
                ('commentedListing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listings')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highestBid', models.PositiveIntegerField()),
                ('noOfBidsMade', models.PositiveIntegerField(default=0)),
                ('madeByUser', models.CharField(max_length=64)),
                ('listedItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.listings')),
            ],
            options={
                'verbose_name_plural': 'Bids',
            },
        ),
    ]
